#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules to run python
module load eb
module load Miniconda2
source deactivate
# loading virtualenv
echo "loading virtualenv"
source activate qiime1
# setting temporary directory
export TMPDIR=~/qiime_tmp
# analysing OTUs diversity
echo "Running Core_Diversity analysis on Silva open reference 2018 OTUs - no Tree parameters"
time core_diversity_analyses.py -i ~/2018/otus/openS/otu_table_mc2otu_table_mc2_w_tax_no_pynast_failures.biom -m ~/2018_02_smb/map_complete.tsv \
--nonphylogenetic_diversity -e 746 -o ~/2018/core_diversity_Silva/openS_noTree -a -O 16
# deactivating environment
source deactivate
