#!/bin/bash
#SBATCH -t 2:00:00
#SBATCH -n 24
#SBATCH -p normal

#Load modules to run python
module load eb
module load Miniconda2
source deactivate
# loading virtualenv
echo "loading virtualenv"
source activate qiime1
# setting temporary directory
export TMPDIR=~/qiime_tmp
# picking OTUs
echo "Picking OTUs with open Silva reference"
time pick_open_reference_otus.py -i ~/2018/slout/seqs_chimeras_filtered.fna/ \
-r ~/ref_database/SILVA_132_QIIME_release/rep_set/rep_set_16S_only/97/silva_132_92_16S.fna \
-o ~/2018/otus/openS -a -O 16
source deactivate
