#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules to run python
module load eb
module load Miniconda2
source deactivate
# loading virtualenv
echo "loading virtualenv"
source activate qiime1
# setting temporary directory
export TMPDIR=~/qiime_tmp
# Keeping only OTUs in park
echo "Split rarefied qual Silva open OTUs - park and non_park"
time split_otu_table.py \
-i ~/2018/Qotus/openS/otu_table_mc2_w_tax_no_pynast_failures.biom \
-m ~/map_complete.tsv \
-o ~/2018/Qotus/SplitOTUs/openS_Park \
-f Location

source deactivate
