#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short
##SBATCH --reservation=cbmucl
#Load modules
module load eb
module load Miniconda2
# loading virtualenv
source activate qiime1
# setting temporary directory
export TMPDIR=~/qiime_tmp
# splitting libraries
echo "splitting libraries"
time split_libraries_fastq.py --rev_comp_barcode --rev_comp_mapping_barcodes -i ~/2018/SeqPrep_Joined/seqprep_assembled.fastq.gz -b ~/2018/SeqPrep_Joined/seqprep_assembled.fastq_barcodes.fastq -q 19 -o ~/2018/Qslout -m ~/2018_02_smb/map_complete.tsv
# counting sequences
echo "Counting sequences"
time count_seqs.py -i ~/2018/Qslout/seqs.fna
# deactivating environment
source deactivate
