#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules to run python
module load eb
module load Miniconda2
source deactivate
# loading virtualenv
echo "loading virtualenv"
source activate qiime1
# setting temporary directory
export TMPDIR=~/qiime_tmp
# analysing OTUs diversity
echo "Running Core_Diversity analysis on closed Silva reference 2018 OTUs - no tax, no tree parameters"
time core_diversity_analyses.py -i ~/2018/otus/closedS_noTax/otu_table.biom -m ~/2018_02_smb/map_complete.tsv \
-e 626 -o ~/2018/core_diversity_Silva/closedS_noTax_noTree -a -O 16
# deactivating environment
source deactivate
