#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules to run python
module load eb
module load Miniconda2
source deactivate
# loading virtualenv
echo "loading virtualenv"
source activate qiime1
# setting temporary directory
export TMPDIR=~/qiime_tmp
# analysing OTUs diversity
echo "Running Core_Diversity analysis on Silva open reference 2018 OTUs"
time core_diversity_analyses.py -i ~/2018/otus/openS/otu_table_mc2.biom -m ~/2018_02_smb/map_complete.tsv -e 746 -o ~/2018/core_diversity/openS -a -O 24
# deactivating environment
source deactivate
