#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules to run python
module load eb
module load Miniconda2
source deactivate
# loading virtualenv
echo "loading virtualenv"
source activate qiime1
module load R
# setting temporary directory
export TMPDIR=~/qiime_tmp
echo "Filtering outlier OTUs from OTU table"
filter_otus_from_otu_table.py -i ~/2018_EMP_analysis/GordonOTUs/otu_table.biom \
-o ~/2018_EMP_analysis/Fotu_table_openSQ.biom \
--min_count_fraction 0.00005

source deactivate
