#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules to run python
module load eb
module load Miniconda2
source deactivate
# loading virtualenv
echo "loading virtualenv"
source activate qiime1
# setting temporary directory
export TMPDIR=~/qiime_tmp
#Merging OTU tables
echo "Merging OTU table from EMP with ours"
time merge_otu_tables.py -i ~/2018_EMP_analysis/BIOM_tables/emp.biom,~/2018_EMP_analysis/GordonOTUs/otu_table.biom \
-o ~/2018_EMP_analysis/BIOM_tables/merged_otu_table.biom
# analysing OTUs diversity
echo "Running Core_Diversity analysis on closed Silva reference 2018 OTUs from quality filtered sequences - with Tax, with Tree parameters"
time core_diversity_analyses.py -i ~/2018_EMP_analysis/BIOM_tables/merged_otu_table.biom \
-m ~/2018_EMP_analysis/emp_map.tsv \
-t ~/ref_database/SILVA123_QIIME_release/trees/97/97_otus.tre \
-e 626 -o ~/2018_EMP_analysis/Core_diversity -a -O 16
# deactivating environment
source deactivate
