#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules to run python
module load eb
module load Miniconda2
source deactivate
# loading virtualenv
echo "loading virtualenv"
source activate qiime1
# setting temporary directory
export TMPDIR=~/qiime_tmp
# picking OTUs
echo "Picking OTUs from quality filtered sequences with closed default reference"
time pick_closed_reference_otus.py -i ~/2018/Qslout/seqs.fna -o ~/2018/Qotus/closedD -a -O 24
source deactivate
