#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules to run python
module load eb
module load Miniconda2
source deactivate
# loading virtualenv
echo "loading virtualenv"
source activate qiime1
# setting temporary directory
export TMPDIR=~/qiime_tmp
# picking OTUs
echo "Picking OTUs with closed default reference - benchmark 24 24"
time pick_closed_reference_otus.py -i ~/2018/Benchmark/slout/seqs.fna -o ~/2018/Benchmark/otus/closedD_24_24 -a -O 24
source deactivate
