#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules to run python
module load eb
module load Miniconda2
source deactivate
# loading virtualenv
echo "loading virtualenv"
source activate qiime1
# setting temporary directory
export TMPDIR=~/qiime_tmp
# picking OTUs
echo "Picking OTUs with open default reference - benchmark 24 16"
time pick_open_reference_otus.py -i ~/2018/Benchmark/slout/seqs.fna -o ~/2018/Benchmark/otus/openD_24_16 -a -O 16
source deactivate
