#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules to run python
module load eb
module load Miniconda2
source deactivate
# loading virtualenv
echo "loading virtualenv"
source activate qiime1
module load R
# setting temporary directory
export TMPDIR=~/qiime_tmp
echo "Making distance matrix from category"
time distance_matrix_from_mapping.py -m ~/2018_02_smb/map_complete.tsv \
-c Geography -o ~/2018/Qcore_diversity/Geography_Mantel/Geography_dm.txt

echo "Comparing distance matrices using Mantel"
time compare_distance_matrices.py -i ~/2018/Qcore_diversity/Geography_Mantel/Geography_dm.txt,~/2018/Qcore_diversity/openS_wTree/bdiv_even651/unweighted_unifrac_dm.txt \
--method mantel -o ~/2018/Qcore_diversity/Geography_Mantel/Mantel
source deactivate
