#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules to run python
module load eb
module load Miniconda2
source deactivate
# loading virtualenv
echo "loading virtualenv"
source activate qiime1
# setting temporary directory
export TMPDIR=~/qiime_tmp
# analysing alpha diversity
echo "Running alpha-diversity on non-filtered OTUs, Q NF Silva open"
time alpha_diversity.py -t ~/2018/Qotus/openS/rep_set.tre \
-i ~/table_even38882.biom \
-o ~/alpha_Div_Shannon_and_Eveness.txt -m shannon,simpson_e,simpson

source deactivate
