#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules to run python
module load eb
module load Miniconda2
source deactivate
# loading virtualenv
echo "loading virtualenv"
source activate qiime1
# setting temporary directory
export TMPDIR=~/qiime_tmp
# Generating biplots 
echo "Making biplots, all samples rarefied unweighted"
time make_emperor.py -m ~/map_complete.tsv \
-t ~/2018/Non_filtered_Analysis/Whole_taxa_plots/otu_table_mc2_w_tax_no_pynast_failures_L2.txt \
-i ~/2018/Non_filtered_Analysis/Qcore_diversity_more/openS_wTree/bdiv_even38882/unweighted_unifrac_pc.txt \
-o ~/biplots/openS_Rare/unweighted --n_taxa_to_keep 5

echo "Making biplots, all samples rarefied weighted"
time make_emperor.py -m ~/map_complete.tsv \
-t ~/2018/Non_filtered_Analysis/Whole_taxa_plots/otu_table_mc2_w_tax_no_pynast_failures_L2.txt \
-i ~/2018/Non_filtered_Analysis/Qcore_diversity_more/openS_wTree/bdiv_even38882/weighted_unifrac_pc.txt \
-o ~/biplots/openS_Rare/weighted --n_taxa_to_keep 5

source deactivate
