#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules to run python
module load eb
module load Miniconda2
module load R
source deactivate
# loading virtualenv
echo "loading virtualenv"
source activate qiime1
# setting temporary directory
export TMPDIR=~/qiime_tmp
# Running beta diveristy on all samples, resulting with NMDS results
echo "Running beta diversity -all NF Silva openSQ, all samples"
time beta_diversity_through_plots.py -m ~/map_complete.tsv \
-i ~/2018/Qotus/openS/otu_table_mc2_w_tax_no_pynast_failures.biom \
-o ~/2018/Non_filtered_Analysis/Qbeta_diversity/openS/DMs \
-t ~/2018/Qotus/openS/rep_set.tre -a -O 16

echo "Running NMDS weighted and unweighted"
time nmds.py -i ~/2018/Non_filtered_Analysis/Qcore_diversity_more/openS_wTree/bdiv_even38882/weighted_unifrac_dm.txt \
-o ~/2018/Non_filtered_Analysis/Qcore_diversity_more/openS_wTree/bdiv_even38882/NMDS_2D_weighted.txt -d 2

time nmds.py -i ~/~/2018/Non_filtered_Analysis/Qcore_diversity_more/openS_wTree/bdiv_even38882/unweighted_unifrac_dm.txt \
-o ~/2018/Non_filtered_Analysis/Qcore_diversity_more/openS_wTree/bdiv_even38882/NMDS_2D_unweighted.txt -d 2

source deactivate
