#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules to run python
module load eb
module load Miniconda2
source deactivate
# loading virtualenv
echo "loading virtualenv"
source activate qiime1
module load R
# setting temporary directory
export TMPDIR=~/qiime_tmp
# Comparing taxonomy
echo "Comparing taxonomy - Geography"
time comapre_taxa_summaries.py -m paired -i table_mc745_sorted_L3.txt,Geography_otu_table_L3.txt \
-o Geography

time comapre_taxa_summaries.py -m paired -i table_mc745_sorted_L3,SampleVegetation_otu_table_L3.txt \
-o Vegetation

source deactivate
