#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules to run python
module load eb
module load Miniconda2
source deactivate
# loading virtualenv
echo "loading virtualenv"
source activate qiime1
module load R
# setting temporary directory
export TMPDIR=~/qiime_tmp
# Looking at common taxonomy within samples
echo "Computing core microbiome rare open Silva qual non-filtered"
time compute_core_microbiome.py \
-i ~/2018/Non_filtered_Analysis/Qcore_diversity_more/table_even38882.biom.gz \
-o ~/2018/Non_filtered_Analysis/Qcore_diversity_more/Core_microbiome/openS/

source deactivate
