#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules to run python
module load eb
module load Miniconda2
source deactivate
# loading virtualenv
echo "loading virtualenv"
source activate qiime1
module load R
# setting temporary directory
export TMPDIR=~/qiime_tmp
# compare alpha diversity
echo "Compare alpha diversity, Geography, Vegetation and SampleID"
time compare_alpha_diversity.py \
-i ~/2018/Non_filtered_Analysis/Qcore_diversity/openS_wTree/arare_max745/alpha_div_collated/PD_whole_tree.txt \
-m ~/2018_02_smb/map_complete.tsv \
-o ~/2018/Non_filtered_Analysis/Qcore_diversity/openS_wTree/CompareAlpha/Geography \
-c Geography

time compare_alpha_diversity.py \
-i ~/2018/Non_filtered_Analysis/Qcore_diversity/openS_wTree/arare_max745/alpha_div_collated/PD_whole_tree.txt \
-m ~/2018_02_smb/map_complete.tsv \
-o /2018/Non_filtered_Analysis/Qcore_diversity/openS_wTree/CompareAlpha/Vegetation \
-c SampleVegetation

time compare_alpha_diversity.py \
-i ~/2018/Non_filtered_Analysis/Qcore_diversity/openS_wTree/arare_max745/alpha_div_collated/PD_whole_tree.txt \
-m ~/2018_02_smb/map_complete.tsv \
-o ~/2018/Non_filtered_Analysis/Qcore_diversity/openS_wTree/CompareAlpha/SampleID \
-c SampleID

source deactivate
