#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules to run python
module load eb
module load Miniconda2
source deactivate
# loading virtualenv
echo "loading virtualenv"
source activate qiime1
module load R
# setting temporary directory
export TMPDIR=~/qiime_tmp
# Looking at common taxonomy within samples
echo "Computing core microbiome open Silva qual non-filtered 50% min"
time compute_core_microbiome.py -i ~/2018/Qotus/openS/otu_table_mc2_w_tax_no_pynast_failures.biom \
-o ~/2018/Non_filtered_Analysis/QCore_Micobiome/openS_SampleID

echo "Same with filtered"
time compute_core_microbiome.py -i ~/2018/Qotus/Fotu_table_openSQ.biom \
-o ~/2018/QCore_Micobiome/openS_SampleID
source deactivate
