#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules to run python
module load eb
module load Miniconda2
source deactivate
# loading virtualenv
echo "loading virtualenv"
source activate qiime1
module load R
# setting temporary directory
export TMPDIR=~/qiime_tmp
# Comparing taxonomy. This script would be located in the adequate folder with all files already present, hence why the path names are short
echo "Comparing taxonomy - 50 and 100"
time compare_taxa_summaries.py -m paired -i core_table_100_L3.txt,core_table_50_L3.txt \
-o 50_and_100

echo "Comparing taxonomy - 100 and all"
time compare_taxa_summaries.py -m paired -i otu_table_park_L3.txt,core_table_100_L3.txt \
-o 100_and_all

echo "Comparing taxonomy - 50 and all"
time compare_taxa_summaries.py -m paired -i otu_table_park_L3.txt,core_table_50_L3.txt.txt \
-o 50_and_all

source deactivate
