#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules to run python
module load eb
module load Miniconda2
source deactivate
# loading virtualenv
echo "loading virtualenv"
source activate qiime1
module load R
# setting temporary directory
export TMPDIR=~/qiime_tmp
# Looking at common taxonomy within samples
echo "Computing core microbiome rare open Silva qual non-filtered"
time compute_core_microbiome.py \
-i ~/2018/Qotus/SplitOTUs/openS_Park/otu_table_mc2_w_tax_no_pynast_failures__Location_Park__.biom \
-o ~/2018/Non_filtered_Analysis/QCore_microbiome/openS_Park/

source deactivate
