#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules to run python
module load eb
module load Miniconda2
source deactivate
# loading virtualenv
echo "loading virtualenv"
source activate qiime1
# setting temporary directory
export TMPDIR=~/qiime_tmp
# analysing OTUs diversity
echo "Running Core_Diversity analysis on filtered Silva open reference 2018 OTUs from quality filtered sequences - with Tree parameters"
time core_diversity_analyses.py \
-i ~/2018/Qotus/Non_F_SplitOTUs/openS_Park/otu_table_mc2_w_tax_no_pynast_failures__Location_Park__.biom \
-m ~/map_complete.tsv --recover_from_failure \
-t ~/2018/Qotus/openS/rep_set.tre \
-e 38882 \
-o ~/openS_wTree_Park -a -O 16
# deactivating environment
source deactivate
