#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules to run python
module load eb
module load Miniconda2
source deactivate
# loading virtualenv
echo "loading virtualenv"
source activate qiime1
module load R
# setting temporary directory
export TMPDIR=~/qiime_tmp
echo "Group significance qual, non fil, Silva open OTUs"
time group_significance.py -i ~/2018/Qotus/openS/otu_table_mc2_w_tax_no_pynast_failures.biom \
-m ~/map_complete.tsv -c Description \
-o ~/2018/Non_filtered_Analysis/Group_Significance_SampleID.txt

echo "Same, Geography, non-filtered"
time group_significance.py -i ~/2018/Qotus/openS/otu_table_mc2_w_tax_no_pynast_failures.biom \
-m ~/map_complete.tsv -c Geography \
-o ~/2018/Non_filtered_Analysis/Group_Significance_Geography.txt

source deactivate
