#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules to run python
module load eb
module load Miniconda2
source deactivate
# loading virtualenv
echo "loading virtualenv"
source activate qiime1
# setting temporary directory
export TMPDIR=~/qiime_tmp
# Performing jacknifed analysis
echo "Performing Jackknifed beta diversity on Open Silva reference OTUs from quality filtered sequences"
time jackknifed_beta_diversity.py -i ~/2018/Qotus/Fotu_table_openSQ.biom \
-m ~/2018_02_smb/map_complete.tsv -e 3000 \
-t ~/2018/Qotus/openS/rep_set.tre \
-o ~/2018/QJackknifed/openS -a -O 16

# Making a Bootstrapped tree
echo "Making bootstrapped tree from Jackknifed output"
time make_bootstrapped_tree.py -m ~/2018/QJackknifed/openS/unweighted_unifrac/upgma_cmp/master_tree.tre \
-s ~/2018/QJackknifed/openS/unweighted_unifrac/upgma_cmp/jackknife_support.txt \
-o ~/2018/QJackknifed/openS/unweighted_unifrac/upgma_cmp/jackknife_bottstrapped_tree.pdf

# Deactivating Environment
source deactivate
