#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules to run python
module load eb
module load Miniconda2
source deactivate
# loading virtualenv
echo "loading virtualenv"
source activate qiime1
module load R
# setting temporary directory
export TMPDIR=~/qiime_tmp
#Procrustes analysis
echo "Performing Procrustes analysis on Core_diversity output"
time transform_coordinate_matrices.py \
-i ~/2018/Qcore_diversity/openS_wTree/bdiv_even745/unweighted_unifrac_pc.txt,~/2018/Qcore_diversity/openS_wTree/bdiv_even745/weighted_unifrac_pc.txt \
-o ~/2018/Qcore_diversity/openS_wTree/procrustes_output

time make_emperor.py -c -i ~/2018/Qcore_diversity/openS_wTree/procrustes_output \
-o ~/2018/Qcore_diversity/openS_wTree/procrustes_output/plots \
-m ~/2018_02_smb/map_complete.tsv
