#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules to run python
module load eb
module load Miniconda2
source deactivate
# loading virtualenv
echo "loading virtualenv"
source activate qiime1
module load R
# setting temporary directory
export TMPDIR=~/qiime_tmp
# Taxa for a single category
echo "Summarise taxa through plots core microbiome rare 50 100"
time summarize_taxa_through_plots.py \
-i ~/2018/Non_filtered_Analysis/QCore_microbiome/openS_Park/core_table_50.biom \
-o ~/2018/Non_filtered_Analysis/QCore_microbiome/openS_Park/50_summary \
-m ~/map_complete.tsv

time summarize_taxa_through_plots.py \
-i ~/2018/Non_filtered_Analysis/QCore_microbiome/openS_Park/core_table_100.biom \
-o ~/2018/Non_filtered_Analysis/QCore_microbiome/openS_Park/100_summary \
-m ~/map_complete.tsv

source deactivate
