#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules to run python
module load eb
module load Miniconda2
source deactivate
# loading virtualenv
echo "loading virtualenv"
source activate qiime1
module load R
# setting temporary directory
export TMPDIR=~/qiime_tmp
# Taxa for a single category
echo "Summarise taxa through plots for geography and vegetation"
time summarize_taxa_through_plots.py -i ~/2018/Qotus/Fotu_table_openSQ.biom \
-o ~/2018/Qcore_diversity/openS_w_Tree/Additional_taxa_plots/Geography \
-m ~/map_complete.tsv -c Geography

time summarize_taxa_through_plots.py -i ~/2018/Qotus/Fotu_table_openSQ.biom \
-o ~/2018/Qcore_diversity/openS_w_Tree/Additional_taxa_plots/Vegetation \
-m ~/map_complete.tsv -c SampleVegetation
source deactivate
