#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules to run python
module load eb
module load Miniconda2
source deactivate
# loading virtualenv
echo "loading virtualenv"
source activate qiime1
module load R
# setting temporary directory
export TMPDIR=~/qiime_tmp
# Taxa for a single category
echo "Summarise taxa through plots for geography and vegetation"
time summarise_taxa_through_plots.py -i ~/2018/Qotus/openS/otu_table_mc2_w_tax_no_pynast_failures.biom \
-o ~/2018/Qcore_diversity/Additional_taxa_plots/Geography \
-m ~/2018_02_smb/map_complete.tsv -c Geography

time summarise_taxa_through_plots.py -i ~/2018/Qotus/openS/otu_table_mc2_w_tax_no_pynast_failures.biom \
-o ~/2018/Qcore_diversity/Additional_taxa_plots/Vegetation \
-m ~/2018_02_smb/map_complete.tsv -c SampleVegetation
source deactivate
