#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules to run python
module load eb
module load Miniconda2
source deactivate
# loading virtualenv
echo "loading virtualenv"
source activate qiime1
# setting temporary directory
export TMPDIR=~/qiime_tmp

# Removing Chimeric sequences
echo "Finding Chimeric sequences, ChimeraSlayer, Quality filtered Silva Open OTUs"
time identify_chimeric_seqs.py ~/2018/Qslout/seqs.fna \
-m usearch61 -o ~/2018/Qslout/usearch_chimeras \
-r ~/ref_database/SILVA_132_QIIME_release/rep_set/rep_set_16S_only/97/silva_132_97_16S.fna

echo "Filtering out chimeric sequences"
filter_fasta.py -f ~/2018/Qslout/seqs.fna -o ~/2018/Qslout/seqs_chimeras_filtered.fna \
-s ~/2018/Qslout/usearch_chimeras/chimeras.txt -n

# Deactivating environment
source deactivate
